### ISSUE TITLE
advantages with in memory sqlite ?

### ISSUE THREAD

**Issue by xcombelle** [tobgu/qcache#2]
I wonder what is the advantage to use this instead of having an in memory sqlite or another in memory database engine (a huge advantage is that database engine work for multiple tables)

**Comment by tobgu** [comment]
That's a relevant question. I see two interpretations of it though (and there are probably additional ones, please let me know by clarifying your question in that case), both equally interesting:

#### Why is QCache not based on SQLite instead of Pandas?

I did some tests initially comparing SQLite with Pandas. Mainly with regards to performance. It turned out that the Pandas solution was faster both at ingesting data and querying it (I don't have the exact numbers anymore unfortunately). This was all done without adding any type of indices to the tables. Adding indices to the tables would have a big positive performance impact on SQLite but would also slow down the ingestion rate further (I believe, I never tested it).
Which leads me to my second point. I wanted the cache to be really flexible and understand the data you fed it automatically just having to state the exceptions with regards to column types, etc. rather than having to specify a schema for each table that you put into the cache.
Having to specify indices to get decent query performance (< 100 ms for tables with 500 000+ rows in them) also spoke against SQLite since I would not be aware of all queries that were going to be run against the tables up front. Having decent performance for in-memory full table scans was essential to get that flexibility.
Pandas also supports indexing of data should the need arise to further increase query performance. It also supports joining of multiple tables (with nice performace as seen here http://wesmckinney.com/blog/high-performance-database-joins-with-pandas-dataframe-more-benchmarks/). In addition to this it is also super flexible in how it allows you to query the data and will allow the query language to be made as powerful as needed.

In essence: SQLite is a really nice piece of SW but for this use case I found Pandas superior.

#### Why not just use a SQLite DB in process in your application instead of this?

Because I wanted to build a cache that could be shared by multiple application instances where the data could be uploaded once and then accessed by any instance.

**Comment by xcombelle** [comment]
Thanks a lot, does your code support multiple table/data frames ?

**Comment by tobgu** [comment]
You can put as many tables as you want (given that they fit in memory) into the cache.

The mapping is:
Key -> Table

There's no need for the data to be uniform (eg. the same columns and types) between tables.

There's currently no support for joining data from one table to that of another or running cross table queries.

**Comment by tobgu** [comment]
I'm closing this issue now. Please re-open it or open a new one if you have more questions.
